### ISSUE TITLE
enableShowMore

### ISSUE THREAD

**Issue by abdelrany** [lohenyumnam/react-native-truncated-text-view#13]
I am suggesting that a "enableShowMore" property should be added to disable the "Show More" button. Currently, i am  using a card product title to limit the number of lines shown in the title. I've successfully disabled the "Show Less" button, but the "Show More" button is still being displayed in the title.

**Comment by lohenyumnam** [comment]
Can you Explain its use case of it?
the main idea, behind this component, is to show the "Show More" part.

**Comment by abdelrany** [comment]
That's true the main  of this is show the "Show More" part, but if you make an other prop to disable it  as enableShowLess  prop, it will be more useful for other parts like titles card descriptions and more.
